### ISSUE TITLE
Delete and re-download thumbnails

### ISSUE THREAD

**Issue by wopian** [wopian/material-slackthemes#12]
Current thumbnails show Channels (2) instead of Channels (3).

**Comment by wopian** [comment]
Done.

**Comment by paracycle** [comment]
James, I'd actually argue that you should delete all the thumbnails in the repo (I'll do the same for the SlackThemes repo myself). The reasons are many:

1. Technically thumbnails should be the output of a build step (and it is), thus these files have no place in the `src` folder.
2. You need PhantomJS 2.0 (or greater) to grab the thumbnails so that the custom font rendering etc works properly. This is ensured on the Travis build, but I can see that this repo has thumbnails that don't look right.

**Comment by wopian** [comment]
Done: https://github.com/wopian/material-slackthemes/commit/2ee7da4d6a6bc881a9ad702dde12e132a96486fd

**Comment by wopian** [comment]
@paracycle, removing all the thumbnails causes the thumbnails to be generated (as expected), but they're not copied to the `gh-pages` branch in the creation stage.

https://travis-ci.org/wopian/material-slackthemes#L275

**Comment by paracycle** [comment]
That shouldn't be the case, I've just deleted all the files in the `source/images/theme` folder and ran `bundle exec middleman build` and observed that the files were generated **and** copied to the `build` folder. Actually that's how SlackThemes has been working since I've switched to doing builds on Travis. This probably needs a little more investigation.

**Comment by paracycle** [comment]
Ok, fixed with 7fcf0b3529fe5f9108f6088e3257a1d945800a9e

**Comment by paracycle** [comment]
So the problem was that the folder `source/images/theme` had to still be in Git so that the generated files could be placed there.

**Comment by paracycle** [comment]
Also note this commit: https://github.com/wopian/material-slackthemes/commit/ac05e05d03589a395f55a6b30213841591ed9c8d

**Comment by paracycle** [comment]
And this one: https://github.com/wopian/material-slackthemes/commit/dcf5fd616fc934704b6be3d03d8468cc8979492f
